# Generated by Django 5.2.4 on 2026-05-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('bible', '0006_biblehighlight_is_active'),
        ('tenants', '0001_initial'),
        ('units', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblechaptercache',
            options={'verbose_name': 'Cached Chapter', 'verbose_name_plural': 'Cached Chapters'},
        ),
        migrations.AlterModelOptions(
            name='biblesharerecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Bible Share Record', 'verbose_name_plural': 'Bible Share Records'},
        ),
        migrations.AlterModelOptions(
            name='biblestudyreference',
            options={'ordering': ['-active_date', '-created_at'], 'verbose_name': 'Bible Study Reference', 'verbose_name_plural': 'Bible Study References'},
        ),
        migrations.AlterModelOptions(
            name='bibletranslationcache',
            options={'ordering': ['translation_id'], 'verbose_name': 'Cached Translation', 'verbose_name_plural': 'Cached Translations'},
        ),
        migrations.AlterModelOptions(
            name='memberbadgeaward',
            options={'ordering': ['-awarded_at'], 'verbose_name': 'Badge Award', 'verbose_name_plural': 'Badge Awards'},
        ),
        migrations.AlterModelOptions(
            name='memberplanprogress',
            options={'verbose_name': 'Member Plan Progress', 'verbose_name_plural': 'Member Plan Progress'},
        ),
        migrations.AlterModelOptions(
            name='memberplanstreak',
            options={'verbose_name': 'Member Plan Streak', 'verbose_name_plural': 'Member Plan Streaks'},
        ),
        migrations.AlterModelOptions(
            name='memoryverse',
            options={'ordering': ['-active_date'], 'verbose_name': 'Memory Verse', 'verbose_name_plural': 'Memory Verses'},
        ),
        migrations.AlterModelOptions(
            name='readingplan',
            options={'ordering': ['-start_date'], 'verbose_name': 'Reading Plan', 'verbose_name_plural': 'Reading Plans'},
        ),
        migrations.AlterModelOptions(
            name='readingplanentry',
            options={'ordering': ['order', 'scheduled_date'], 'verbose_name': 'Reading Plan Entry', 'verbose_name_plural': 'Reading Plan Entries'},
        ),
        migrations.RemoveConstraint(
            model_name='biblechaptercache',
            name='bible_chapter_unique',
        ),
        migrations.RemoveIndex(
            model_name='biblehighlight',
            name='bible_hl_church_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='biblehighlight',
            name='bible_hl_church_active_idx',
        ),
        migrations.RenameIndex(
            model_name='biblechaptercache',
            new_name='bible_bible_transla_a0148a_idx',
            old_name='bible_chapter_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='biblehighlight',
            new_name='bible_bible_member__fa997f_idx',
            old_name='bible_hl_member_book_ch_idx',
        ),
        migrations.RenameIndex(
            model_name='biblesharerecord',
            new_name='bible_bible_church__010704_idx',
            old_name='bible_share_member_idx',
        ),
        migrations.RenameIndex(
            model_name='memberbadgeaward',
            new_name='bible_membe_church__224c29_idx',
            old_name='bible_award_member_idx',
        ),
        migrations.RenameIndex(
            model_name='memberplanprogress',
            new_name='bible_membe_member__f61616_idx',
            old_name='bible_mpp_member_plan_idx',
        ),
        migrations.RenameIndex(
            model_name='memoryverse',
            new_name='bible_memor_church__752168_idx',
            old_name='bible_memverse_idx',
        ),
        migrations.RenameIndex(
            model_name='readingplan',
            new_name='bible_readi_church__19ce51_idx',
            old_name='bible_plan_published_idx',
        ),
        migrations.RenameIndex(
            model_name='readingplandiscussion',
            new_name='bible_readi_plan_id_0e63ab_idx',
            old_name='bible_disc_plan_entry_idx',
        ),
        migrations.RenameIndex(
            model_name='readingplandiscussion',
            new_name='bible_readi_church__7c8ef8_idx',
            old_name='bible_disc_church_scope_idx',
        ),
        migrations.RenameIndex(
            model_name='readingplanentry',
            new_name='bible_readi_plan_id_c0244e_idx',
            old_name='bible_entry_date_idx',
        ),
        migrations.RenameIndex(
            model_name='readingplanentry',
            new_name='bible_readi_plan_id_9ee40d_idx',
            old_name='bible_entry_order_idx',
        ),
        migrations.AddField(
            model_name='readingplandiscussion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='apibibletranslationmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apibibletranslationmap',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biblehighlight',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='biblehighlight',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='biblehighlight',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='biblehighlight',
            name='note',
            field=models.TextField(blank=True, help_text='Optional personal note on this verse.'),
        ),
        migrations.AlterField(
            model_name='biblesharerecord',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='biblestudyreference',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='memberbadgeaward',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='membermemoryverseprogress',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='memberplanprogress',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='memberplanstreak',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='memberstudyprogress',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='memoryverse',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='readingplan',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='readingplandiscussion',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='readingplandiscussion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='readingplandiscussion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='readingplandiscussion',
            name='is_admin_prompt',
            field=models.BooleanField(default=False, help_text='Admins/leaders start conversations; members ask questions.'),
        ),
        migrations.AlterField(
            model_name='readingplandiscussion',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="Set when scope='unit'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_discussions', to='units.churchunit'),
        ),
        migrations.AlterField(
            model_name='readingplanentry',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AlterField(
            model_name='readingplanentry',
            name='devotional_body',
            field=models.TextField(blank=True, help_text='Inspirational content body. Use [REF:John 3:16] markers to embed inline Bible references that expand when clicked.'),
        ),
        migrations.AlterField(
            model_name='readingplanentry',
            name='inline_references',
            field=models.JSONField(blank=True, default=list, help_text='Additional Bible references cited in this devotional entry.'),
        ),
        migrations.AlterUniqueTogether(
            name='biblechaptercache',
            unique_together={('translation', 'book_id', 'chapter')},
        ),
        migrations.AddIndex(
            model_name='memberplanprogress',
            index=models.Index(fields=['plan', 'entry'], name='bible_membe_plan_id_beb6f7_idx'),
        ),
    ]
