# Generated by Django 5.2.4 on 2026-05-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0007_alter_biblechaptercache_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingplanentry',
            name='chapter_to',
            field=models.PositiveSmallIntegerField(blank=True, help_text='End chapter of a range (e.g. 3 for Genesis 1–3). Null = single chapter.', null=True),
        ),
    ]
