# Generated by Django 5.2.4 on 2026-06-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0011_youversion_oauth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youversionoauthtoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='youversionoauthtoken',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
