# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feeds', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a church-wide (general workforce) post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_posts', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feeds.feedcomment'),
        ),
        migrations.AddField(
            model_name='feedmedia',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='feedmedia',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feednotification',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feednotification',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='feednotification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to='feeds.feedcomment'),
        ),
        migrations.AddField(
            model_name='feednotification',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_notifs', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feednotification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedreaction',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='feedreaction',
            name='feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedrepost',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='feedrepost',
            name='original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedrepost',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposted_from', to='feeds.feed'),
        ),
        migrations.AddField(
            model_name='feedrepost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_reposts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['church', 'scope', '-created_at'], name='feeds_feed_church__daa59e_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['church', 'unit', '-created_at'], name='feeds_feed_church__e00d8c_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['church', 'is_pinned', '-created_at'], name='feeds_feed_church__537c30_idx'),
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['feed', 'parent', 'created_at'], name='feeds_feedc_feed_id_bdc6dd_idx'),
        ),
        migrations.AddIndex(
            model_name='feednotification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='feeds_feedn_recipie_fc85b2_idx'),
        ),
        migrations.AddIndex(
            model_name='feedreaction',
            index=models.Index(fields=['feed', 'reaction'], name='feeds_feedr_feed_id_4e349e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='feedreaction',
            unique_together={('feed', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='feedrepost',
            unique_together={('original', 'user')},
        ),
    ]
