# Generated by Django 5.2.4 on 2026-05-16 20:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feedreaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feedreaction',
            name='reaction',
            field=models.CharField(choices=[('like', '👍 Like'), ('love', '❤️ Love'), ('fire', '🔥 Fire'), ('pray', '🙏 Pray'), ('clap', '👏 Clap'), ('amen', '🙌 Amen'), ('bless', '✨ Bless'), ('inspired', '💡 Inspired'), ('plugged', '🔌 Plugged'), ('peace', '🕊️ Peace'), ('thanks', '🤝 Thanks'), ('joy', '😊 Joy'), ('wow', '😮 Wow'), ('blessed', '⭐ Blessed'), ('bible', '📖 Bible'), ('faith', '✝️ Faith'), ('hope', '🌱 Hope'), ('following', '👥 Following'), ('checkmate', '♟️ Checkmate')], default='like', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='feedreaction',
            unique_together={('feed', 'user', 'reaction')},
        ),
    ]
