# Generated by Django 5.2.4 on 2026-03-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinvitation',
            name='suggested_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='units.churchunit'),
        ),
        migrations.AddIndex(
            model_name='churchmember',
            index=models.Index(fields=['church', 'user'], name='accounts_ch_church__562a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='churchmember',
            index=models.Index(fields=['church', 'custom_id'], name='accounts_ch_church__f088d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchmember',
            constraint=models.UniqueConstraint(fields=('church', 'user'), name='unique_user_per_church'),
        ),
        migrations.AddConstraint(
            model_name='churchmember',
            constraint=models.UniqueConstraint(fields=('church', 'custom_id'), name='unique_member_custom_id_per_church'),
        ),
        migrations.AddIndex(
            model_name='memberinvitation',
            index=models.Index(fields=['church', 'email'], name='accounts_me_church__bd52ae_idx'),
        ),
        migrations.AddIndex(
            model_name='memberinvitation',
            index=models.Index(fields=['token'], name='accounts_me_token_6561cc_idx'),
        ),
    ]
