# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('category', models.CharField(choices=[('manual', 'Manual bulk message'), ('birthday', 'Birthday message'), ('reminder', 'Follow-up reminder'), ('other', 'Other automated')], db_index=True, default='manual', max_length=20)),
                ('provider', models.CharField(blank=True, help_text='SMS provider used (termii, africastalking, twilio, etc.)', max_length=50)),
                ('provider_reference', models.CharField(blank=True, help_text="Provider's message ID for delivery status lookup.", max_length=255)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('recipients', models.ManyToManyField(blank=True, related_name='received_messages', to='guests.guestentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
