# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0002_initial'),
        ('messaging', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestmessage',
            name='sender',
            field=models.ForeignKey(help_text='The workforce member who sent this message.', on_delete=django.db.models.deletion.CASCADE, related_name='sent_guest_messages', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='messagelog',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='messaging.guestmessage'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['church', 'status'], name='messaging_m_church__cea39d_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['church', 'category'], name='messaging_m_church__1f3569_idx'),
        ),
        migrations.AddIndex(
            model_name='messagelog',
            index=models.Index(fields=['church', '-created_at'], name='messaging_m_church__1df44c_idx'),
        ),
    ]
