# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('trial', 'Trial'), ('saas', 'SaaS'), ('white_label', 'White Label'), ('founders_saas_lifetime', 'Founders SaaS Lifetime'), ('founders_white_label_lifetime', 'Founders White Label Lifetime')], max_length=50, unique=True)),
                ('multi_campus', models.BooleanField(default=False)),
                ('white_label', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('monthly_price_ngn', models.PositiveIntegerField(default=0, help_text='Monthly price in Naira. Set 0 for free or lifetime plans.')),
                ('campus_limit', models.SmallIntegerField(default=0, help_text="Maximum number of campuses. '0' = none (trial); '-1' = unlimited; 'n' = capped.")),
                ('campus_price_ngn', models.PositiveIntegerField(default=0, help_text="Additional cost in Naira per campus above the plan's base allowance.")),
            ],
        ),
        migrations.CreateModel(
            name='ChurchSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual (10% off)'), ('biannual', 'Bi-annual (20% off)')], default='monthly', max_length=20)),
                ('is_trial', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('reminder_7d_sent', models.BooleanField(default=False)),
                ('reminder_3d_sent', models.BooleanField(default=False)),
                ('reminder_1d_sent', models.BooleanField(default=False)),
                ('paystack_subscription_code', models.CharField(blank=True, default='', help_text='Paystack subscription code for recurring billing.', max_length=100)),
                ('paystack_email_token', models.CharField(blank=True, default='', help_text='Paystack email token for manage-subscription link.', max_length=200)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='churchsubscription', to='tenants.church')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual (10% off)'), ('biannual', 'Bi-annual (20% off)')], default='monthly', max_length=20)),
                ('reference', models.CharField(db_index=True, help_text='Paystack transaction reference.', max_length=100, unique=True)),
                ('amount_ngn', models.PositiveIntegerField(help_text='Amount charged in Naira.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], db_index=True, default='pending', max_length=20)),
                ('paystack_event', models.CharField(blank=True, help_text='Paystack event type, e.g. charge.success', max_length=100)),
                ('raw_payload', models.JSONField(blank=True, default=dict, help_text='Full Paystack webhook payload for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='tenants.church')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', '-created_at'], name='billing_pay_church__244c3a_idx'), models.Index(fields=['reference'], name='billing_pay_referen_aa4820_idx'), models.Index(fields=['status'], name='billing_pay_status_04ed08_idx')],
            },
        ),
    ]
