# Generated by Django 5.2.4 on 2026-03-23 19:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Service', 'Service'), ('Meeting', 'Meeting'), ('Training', 'Training'), ('Rehearsal', 'Rehearsal'), ('Outreach', 'Outreach'), ('Other', 'Other')], max_length=50)),
                ('attendance_mode', models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='Physical', max_length=10)),
                ('day_of_week', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days this event lasts.')),
                ('is_recurring_weekly', models.BooleanField(default=False)),
                ('postponed', models.BooleanField(default=False)),
                ('event_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image')),
                ('registrable', models.BooleanField(default=False, help_text='Allow members to register for this event.')),
                ('registration_link', models.URLField(blank=True, max_length=500, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='accounts.churchmember')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'day_of_week', 'time'],
            },
        ),
    ]
