# Generated by Django 5.2.4 on 2026-05-09 09:57

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('lms', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Stable public identifier used in URLs instead of pk.', unique=True)),
                ('name', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('Service', 'Service'), ('Meeting', 'Meeting'), ('Training', 'Training'), ('Rehearsal', 'Rehearsal'), ('Outreach', 'Outreach'), ('Other', 'Other')], max_length=50)),
                ('count_towards_commitment', models.BooleanField(db_index=True, default=False, help_text="Count attendance at this event toward a guest's commitment threshold. Enable for main services; disable for unit meetings, training days, or one-off events.")),
                ('attendance_mode', models.CharField(choices=[('Physical', 'Physical'), ('Virtual', 'Virtual'), ('Hybrid', 'Hybrid')], default='Physical', max_length=10)),
                ('day_of_week', models.CharField(blank=True, choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=20, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('attendance_closes_at', models.TimeField(blank=True, help_text='Optional end time used to close attendance access.', null=True)),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Number of days this event lasts.')),
                ('is_recurring_weekly', models.BooleanField(default=False)),
                ('postponed', models.BooleanField(default=False)),
                ('event_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_image')),
                ('registrable', models.BooleanField(default=False, help_text='Allow members to register for this event.')),
                ('registration_link', models.URLField(blank=True, max_length=500, null=True)),
                ('trainee_access', models.BooleanField(default=False, help_text='When checked, trainees in the guest pipeline can see and mark attendance for this event. Uncheck to hide it from trainees.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to='accounts.churchmember')),
                ('lms_course', models.ForeignKey(blank=True, help_text='For Training events only — link to the LMS course this session covers. Trainee attendance at this event unlocks the course for them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_events', to='lms.lmscourse')),
                ('modules_covered', models.ManyToManyField(blank=True, help_text='For Training events — which course modules this class covers. Leave empty to unlock all modules on attendance. Select specific modules to unlock only those.', related_name='training_events', to='lms.lmsmodule')),
                ('prepares_for_service', models.ForeignKey(blank=True, help_text='For Rehearsal events only — link to the Event this rehearsal is preparing for. This connection is visible on the rehearsal board.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsal_preparations', to='services.event')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['date', 'day_of_week', 'time'],
            },
        ),
    ]
