# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Leave blank for church-wide events visible to all units.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='units.churchunit'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['church', 'name'], name='services_ev_church__0c6268_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['church', 'event_type'], name='services_ev_church__f7a3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['church', 'date'], name='services_ev_church__857002_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['church', 'unit'], name='services_ev_church__7c96c6_idx'),
        ),
    ]
