# Generated by Django 5.2.4 on 2026-03-23 19:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('finalized', models.BooleanField(default=False, help_text='Mark true when the setlist is approved and locked.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetlistSong',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('performance_key', models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], help_text="Key for this performance (may differ from track's original key).", max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Service-specific notes: cues, key changes, duration, etc.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('original_key', models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], help_text='Original recorded key of the song.', max_length=5)),
                ('tempo', models.PositiveIntegerField(blank=True, help_text='Beats per minute (BPM).', null=True)),
                ('spotify_id', models.CharField(blank=True, max_length=100)),
                ('ccli_id', models.CharField(blank=True, help_text='CCLI song number for licensing reference.', max_length=50)),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, help_text='Audio reference file (MP3/WAV).', max_length=255, null=True, verbose_name='audio')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ChordChart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], max_length=5)),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. 'Acoustic', 'Band default', 'Capo 2'.", max_length=100)),
                ('content', models.TextField(blank=True, help_text='Chord chart text (Nashville number, chord names, or tab).')),
                ('flat_score_id', models.CharField(blank=True, help_text='Flat.io score ID for interactive notation.', max_length=100)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='PDF or image chord chart upload.', max_length=255, null=True, verbose_name='chord_chart')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chord_charts', to='accounts.churchmember')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='RehearsalSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
