# Generated by Django 5.2.4 on 2026-05-09 09:57

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('finalized', models.BooleanField(default=False, help_text='Lock and trigger media sync when True.')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SetlistSong',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('performance_key', models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], help_text='Key for this performance (may differ from original).', max_length=5)),
                ('notes', models.TextField(blank=True, help_text='Cues, key changes, duration notes.')),
                ('sections_to_project', models.JSONField(blank=True, help_text='Ordered list of LyricsSection PKs to project. Null = all sections in order.', null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SetlistSongAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('instrument', models.CharField(choices=[('vocals_lead', 'Lead Vocals'), ('vocals_bg', 'Background Vocals'), ('piano', 'Piano / Keys'), ('electric_guitar', 'Electric Guitar'), ('acoustic_guitar', 'Acoustic Guitar'), ('bass_guitar', 'Bass Guitar'), ('drums', 'Drums / Percussion'), ('violin', 'Violin'), ('trumpet', 'Trumpet'), ('saxophone', 'Saxophone'), ('flute', 'Flute'), ('cello', 'Cello'), ('sound', 'Sound Engineer'), ('slides', 'Slides Operator'), ('other', 'Other')], default='other', max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Specific notes for this musician on this song.')),
                ('confirmed', models.BooleanField(default=False, help_text='Has the musician confirmed?')),
            ],
            options={
                'ordering': ['instrument', 'member__user__full_name'],
            },
        ),
        migrations.CreateModel(
            name='SongMixPreset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(default='My Mix', max_length=80)),
                ('transpose_semitones', models.SmallIntegerField(default=0)),
                ('channel_state', models.JSONField(blank=True, default=dict)),
                ('strip_order', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SongResource',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=120)),
                ('resource_type', models.CharField(choices=[('chord_chart', 'Chord Chart'), ('sheet_music', 'Sheet Music'), ('stem', 'Stem / Track'), ('loop', 'Loop'), ('reference', 'Reference Recording'), ('lyrics', 'Lyrics Sheet'), ('other', 'Other')], default='other', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='resource')),
                ('external_url', models.URLField(blank=True, help_text='External link (Google Drive, Dropbox, etc.)')),
            ],
            options={
                'ordering': ['resource_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SongStem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=80)),
                ('family', models.CharField(choices=[('vox', 'Vocals'), ('drums', 'Drums'), ('bass', 'Bass'), ('keys', 'Keys'), ('guitar', 'Guitar'), ('fx', 'FX'), ('click', 'Click'), ('other', 'Other')], default='other', max_length=20)),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, help_text='Stem audio file (wav/mp3/aac).', max_length=255, null=True, verbose_name='audio')),
                ('default_gain', models.FloatField(default=0.8, help_text='0.0 - 1.0')),
                ('default_pan', models.FloatField(default=0.0, help_text='-1.0 (L) to 1.0 (R)')),
                ('default_muted', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('artist', models.CharField(blank=True, max_length=255)),
                ('original_key', models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], max_length=5)),
                ('time_signature', models.CharField(blank=True, choices=[('4/4', '4/4'), ('3/4', '3/4'), ('6/8', '6/8'), ('2/4', '2/4'), ('12/8', '12/8'), ('5/4', '5/4')], default='', max_length=5)),
                ('tempo', models.PositiveIntegerField(blank=True, help_text='BPM.', null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Track duration in seconds.', null=True)),
                ('lyrics', models.TextField(blank=True, help_text='Full lyrics text. Sections are structured separately.')),
                ('lyrics_auto', models.BooleanField(default=False, help_text='True if lyrics were auto-transcribed by Whisper.')),
                ('spotify_id', models.CharField(blank=True, max_length=100)),
                ('ccli_id', models.CharField(blank=True, help_text='CCLI song number for licensing.', max_length=50)),
                ('youtube_url', models.URLField(blank=True, help_text='Reference YouTube video.')),
                ('apple_music_url', models.URLField(blank=True)),
                ('audio_file', cloudinary.models.CloudinaryField(blank=True, help_text='Reference audio (MP3/WAV).', max_length=255, null=True, verbose_name='audio')),
                ('audio_transcribed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='TrackTag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=60)),
                ('color', models.CharField(default='#6366f1', help_text='Hex color for UI display.', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ChordChart',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('key', models.CharField(choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], max_length=5)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Acoustic', 'Capo 2', 'Band default'.", max_length=100)),
                ('content', models.TextField(blank=True, help_text='Chord chart text (Nashville number, chord names, tab).')),
                ('flat_score_id', models.CharField(blank=True, help_text='Flat.io score ID for interactive notation.', max_length=100)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='PDF or image upload.', max_length=255, null=True, verbose_name='chord_chart')),
                ('is_default', models.BooleanField(default=False, help_text='Default chart shown when opening the track.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chord_charts', to='accounts.churchmember')),
            ],
            options={
                'ordering': ['-is_default', 'key'],
            },
        ),
        migrations.CreateModel(
            name='LyricsSection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section_type', models.CharField(choices=[('intro', 'Intro'), ('verse', 'Verse'), ('pre_chorus', 'Pre-Chorus'), ('chorus', 'Chorus'), ('bridge', 'Bridge'), ('outro', 'Outro'), ('tag', 'Tag'), ('interlude', 'Interlude'), ('spoken', 'Spoken Word')], default='verse', max_length=20)),
                ('label', models.CharField(blank=True, help_text="e.g. 'Verse 1', 'Chorus 2'. Auto-generated if blank.", max_length=60)),
                ('content', models.TextField(help_text='Lyrics for this section.')),
                ('repeat_count', models.PositiveSmallIntegerField(default=1, help_text='How many times this section repeats.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MixNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('channel_settings', models.JSONField(blank=True, default=dict, help_text='Per-instrument/channel level and EQ notes.')),
                ('fx_notes', models.TextField(blank=True, help_text='Effects and processing notes.')),
                ('general_note', models.TextField(blank=True)),
                ('bpm_used', models.PositiveIntegerField(blank=True, help_text='Actual BPM used in this performance.', null=True)),
                ('key_used', models.CharField(blank=True, choices=[('C', 'C'), ('Cm', 'C minor'), ('C#', 'C#'), ('C#m', 'C# minor'), ('Db', 'Db'), ('D', 'D'), ('Dm', 'D minor'), ('Eb', 'Eb'), ('Ebm', 'Eb minor'), ('E', 'E'), ('Em', 'E minor'), ('F', 'F'), ('Fm', 'F minor'), ('F#', 'F#'), ('F#m', 'F# minor'), ('Gb', 'Gb'), ('G', 'G'), ('Gm', 'G minor'), ('Ab', 'Ab'), ('Abm', 'Ab minor'), ('A', 'A'), ('Am', 'A minor'), ('Bb', 'Bb'), ('Bbm', 'Bb minor'), ('B', 'B'), ('Bm', 'B minor')], max_length=5)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mix_notes', to='accounts.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='RehearsalSession',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('recording_url', models.URLField(blank=True, help_text='Link to rehearsal recording.')),
                ('recording_file', cloudinary.models.CloudinaryField(blank=True, help_text='Uploaded rehearsal recording shared with unit members.', max_length=255, null=True, verbose_name='audio')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
