# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('music', '0002_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rehearsalsession',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsals', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_setlists', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='event',
            field=models.OneToOneField(blank=True, help_text='The service or event this setlist is prepared for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlist', to='services.event'),
        ),
        migrations.AddField(
            model_name='setlist',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The music/worship unit responsible for this setlist.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setlists', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='rehearsalsession',
            name='setlist',
            field=models.ForeignKey(blank=True, help_text='The setlist being rehearsed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rehearsals', to='music.setlist'),
        ),
        migrations.AddField(
            model_name='setlistsong',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='setlistsong',
            name='setlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='music.setlist'),
        ),
        migrations.AddField(
            model_name='track',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_tracks', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='track',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='track',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Leave blank to make available to all units.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='setlistsong',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setlist_appearances', to='music.track'),
        ),
        migrations.AddField(
            model_name='chordchart',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chord_charts', to='music.track'),
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['church', 'unit'], name='music_setli_church__3e7f0c_idx'),
        ),
        migrations.AddIndex(
            model_name='setlist',
            index=models.Index(fields=['church', 'event'], name='music_setli_church__5d40e1_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['church', 'title'], name='music_track_church__701a7e_idx'),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['church', 'unit'], name='music_track_church__1cb972_idx'),
        ),
        migrations.AddConstraint(
            model_name='track',
            constraint=models.UniqueConstraint(fields=('church', 'title', 'artist'), name='unique_track_per_church'),
        ),
        migrations.AddConstraint(
            model_name='setlistsong',
            constraint=models.UniqueConstraint(fields=('setlist', 'track'), name='unique_song_per_setlist'),
        ),
        migrations.AddConstraint(
            model_name='chordchart',
            constraint=models.UniqueConstraint(fields=('track', 'key', 'label'), name='unique_chart_per_track_key_label'),
        ),
    ]
