# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('children', '0001_initial'),
        ('guests', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinsession',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_checkin_sessions', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='children.checkinsession'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='guardian_guest',
            field=models.ForeignKey(blank=True, help_text='Parent/guardian still in the guest pipeline.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_guardians', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='guardian_member',
            field=models.ForeignKey(blank=True, help_text='Parent/guardian who is a church member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_guardians', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='Children ministry unit responsible for this child.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children_profiles', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='checkinrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='children.childprofile'),
        ),
        migrations.AddField(
            model_name='parentcontact',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='children.childprofile'),
        ),
        migrations.AddField(
            model_name='parentcontact',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddIndex(
            model_name='checkinsession',
            index=models.Index(fields=['church', 'session_date'], name='children_ch_church__5de7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['church', 'unit'], name='children_ch_church__227b23_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['church', 'last_name'], name='children_ch_church__7ff873_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['church', 'session'], name='children_ch_church__a55cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='checkinrecord',
            index=models.Index(fields=['church', 'child'], name='children_ch_church__0c76fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='checkinrecord',
            constraint=models.UniqueConstraint(fields=('church', 'child', 'session'), name='unique_child_checkin_per_session'),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=models.Index(fields=['church', 'child'], name='children_pa_church__f0aec8_idx'),
        ),
        migrations.AddIndex(
            model_name='parentcontact',
            index=models.Index(fields=['church', 'is_primary'], name='children_pa_church__29e496_idx'),
        ),
    ]
