# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.core.validators
import django.db.models.deletion
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('bootstrap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('growth_stage', models.CharField(blank=True, db_index=True, help_text='Optional campus growth stage label (configurable per church).', max_length=50)),
                ('contributes_to_parent_metrics', models.BooleanField(default=True, help_text='If True, this campus guest/attendance counts roll up to the parent campus metrics report.')),
                ('workspace_config', models.JSONField(blank=True, default=tenants.models.default_campus_workspace_config, help_text='Campus branch workspace overrides and inheritance flags.')),
                ('location_name', models.SlugField(blank=True, help_text="Short location identifier, e.g. 'abuja'. Drives slug/subdomain generation.", max_length=63)),
                ('campus_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_campuses', to='accounts.churchmember')),
                ('report_to', models.ForeignKey(blank=True, help_text='Parent campus this campus reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campuses', to='tenants.campus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slogan', models.CharField(blank=True, help_text='Optional church slogan shown across the app.', max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('subdomain', models.SlugField(blank=True, null=True, unique=True)),
                ('custom_domain', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org_logos/')),
                ('primary_color', models.CharField(default='#206bc4', max_length=20)),
                ('hide_platform_credit', models.BooleanField(default=False, help_text="Hide 'Powered by ChurchForce' in the footer for white-label deployments.")),
                ('latitude', models.DecimalField(decimal_places=6, help_text="Latitude of the church's primary venue. Required for attendance geo-fencing.", max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text="Longitude of the church's primary venue. Required for attendance geo-fencing.", max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('attendance_radius_km', models.DecimalField(decimal_places=3, default=0.1, help_text='Maximum distance in kilometres from the venue coordinates within which a clock-in or clock-out is accepted. Default: 0.100 (100 metres).', max_digits=5)),
                ('timezone', models.CharField(default='UTC', help_text="Church local timezone. Used for event scheduling and dashboard date display. e.g. 'Africa/Lagos'.", max_length=63)),
                ('campus_location_name', models.SlugField(blank=True, help_text='Short location identifier for this campus-church. Used to build slug/subdomain relative to the parent church.', max_length=63)),
                ('hq_override', models.JSONField(blank=True, default=dict, help_text='HQ-managed feature-flag and restriction overrides for this campus-church.')),
                ('parent_church', models.ForeignKey(blank=True, help_text='HQ church this campus-church reports to. Null = this IS the HQ (or a standalone) church.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_churches', to='tenants.church')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootstrap.churchtemplate')),
            ],
            options={
                'verbose_name': 'church',
                'verbose_name_plural': 'churches',
            },
        ),
        migrations.CreateModel(
            name='CampusMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text="The member's primary campus (home base).")),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tenants.campus')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_memberships', to='accounts.churchmember')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'db_table': 'units_campusmembership',
            },
        ),
        migrations.AddField(
            model_name='campus',
            name='campus_church',
            field=models.OneToOneField(blank=True, help_text='The full Church instance provisioned for this campus. Set automatically on campus creation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campus_record', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='campus',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.CreateModel(
            name='ChurchSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus_growth_stages', models.JSONField(default=tenants.models.default_campus_growth_stages, help_text='Optional list of campus growth stage labels to show in the UI. Leave empty to allow free-text entry.')),
                ('committed_attendance_threshold', models.PositiveSmallIntegerField(default=4, help_text='Number of service attendances within the rolling window that qualifies a guest as Committed. Default: 4.')),
                ('committed_attendance_window_weeks', models.PositiveSmallIntegerField(default=6, help_text='Rolling window in weeks for counting attendances. Default: 6.')),
                ('member_id_prefix', models.CharField(default='MBR', help_text='Prefix for member IDs. e.g. MBR â†’ MBR000001. 2â€“6 uppercase letters.', max_length=6)),
                ('guest_id_prefix', models.CharField(default='GST', help_text='Prefix for guest IDs. e.g. GST â†’ GST000001. 2â€“6 uppercase letters.', max_length=6)),
                ('date_format', models.CharField(default='%d %b %Y', help_text='Python strftime format for displaying dates in the UI. Default: %d %b %Y (e.g. 14 Jun 2025).', max_length=20)),
                ('time_format', models.CharField(default='%H:%M:%S', help_text='Python strftime format for displaying times in the UI. Default: %H:%M:%S (e.g. 14:30:00).', max_length=20)),
                ('thankyou_first_visit_message', models.TextField(blank=True, default="Hi {name}! Thank you for visiting us today. We hope you felt right at home. We'd love to see you again!", help_text='SMS sent to a guest after their first visit. Use {name} for guest name.')),
                ('thankyou_second_visit_message', models.TextField(blank=True, default='Hi {name}! Great to see you again! Your continued presence means a lot to us.', help_text="SMS sent after a guest's second visit. Use {name} for guest name.")),
                ('send_first_visit_thankyou', models.BooleanField(default=True)),
                ('send_second_visit_thankyou', models.BooleanField(default=True)),
                ('enable_guest_module', models.BooleanField(default=True, help_text='Show the guest management module to guest unit members.')),
                ('enable_music_module', models.BooleanField(default=True, help_text='Show the music/setlist module to music unit members.')),
                ('enable_media_module', models.BooleanField(default=True, help_text='Show the media/production module to media unit members.')),
                ('enable_children_module', models.BooleanField(default=False, help_text='Show the children ministry module to children unit members.')),
                ('enable_youth_module', models.BooleanField(default=False, help_text='Show the youth ministry module to youth unit members.')),
                ('enable_teenagers_module', models.BooleanField(default=False, help_text='Show the teenagers ministry module to teenagers unit members.')),
                ('enable_sms_birthday', models.BooleanField(default=True, help_text='Send automated birthday SMS to guests and members.')),
                ('enable_sms_bulk', models.BooleanField(default=True, help_text='Allow manual bulk SMS to guests.')),
                ('enable_welcome_screen', models.BooleanField(default=True, help_text='Show the welcome/quote screen after login before entering the dashboard.')),
                ('username_prefix', models.CharField(blank=True, help_text='Optional username prefix, e.g. @', max_length=20)),
                ('username_use_church_slug_suffix', models.BooleanField(default=False, help_text="Append '.<church-slug>' to usernames for church-scoped uniqueness.")),
                ('core_values', models.JSONField(blank=True, default=list, help_text='List of church core values/tenets. Each entry: {"title": "...", "description": "..."}. Used by AI skills for personalisation across the system.')),
                ('vision_statement', models.TextField(blank=True, help_text='Church vision statement. Used by AI for context-aware messaging.')),
                ('mission_statement', models.TextField(blank=True, help_text='Church mission statement.')),
                ('denominational_affiliation', models.CharField(blank=True, help_text='e.g. Pentecostal, Baptist, Anglican, Non-denominational.', max_length=100)),
                ('lms_config', models.JSONField(blank=True, default=dict, help_text='LMS pipeline integration settings. Keys: induction_course_type, default_passing_score, promotion_mode, promotion_approval_role, allow_retakes_default, max_retakes_default, notify_unit_head_on_completion, notify_admin_on_completion.')),
                ('workforce_config', models.JSONField(blank=True, default=dict, help_text='Workforce pipeline settings. Keys: default_workforce_stage, absence_flag_threshold.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='tenants.church')),
            ],
            options={
                'verbose_name': 'church setting',
                'verbose_name_plural': 'church settings',
            },
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['slug'], name='tenants_chu_slug_db782d_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['subdomain'], name='tenants_chu_subdoma_2338c4_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['custom_domain'], name='tenants_chu_custom__6c5bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['is_active'], name='tenants_chu_is_acti_1b0959_idx'),
        ),
        migrations.AddIndex(
            model_name='church',
            index=models.Index(fields=['parent_church'], name='tenants_chu_parent__73e16c_idx'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['church', 'campus'], name='units_campu_church__a5183c_idx'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['church', 'member'], name='units_campu_church__cf3d8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='campusmembership',
            constraint=models.UniqueConstraint(fields=('member', 'campus'), name='unique_campus_membership'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['church', 'growth_stage'], name='tenants_cam_church__c4eb17_idx'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('church', 'slug'), name='unique_campus_slug_per_church'),
        ),
    ]
