# Generated by Django 5.2.4 on 2026-03-22 01:00

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('note', models.TextField()),
                ('service_sunday', models.BooleanField(default=False)),
                ('service_midweek', models.BooleanField(default=False)),
                ('service_others', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('contact_attempted', models.BooleanField(default=False)),
                ('contact_answered', models.BooleanField(default=False, help_text="Set True when the guest responds. Triggers 'In-Contact' status.")),
                ('contact_type', models.CharField(blank=True, choices=[('call', 'Phone call'), ('text', 'Text / chat message'), ('visit', 'Physical visit')], max_length=10)),
                ('contact_attachment', models.FileField(blank=True, help_text='Optional screenshot of a text/chat conversation as evidence.', null=True, upload_to='contact_screenshots/%Y/%m/')),
                ('not_planted', models.BooleanField(default=False, help_text="Set True if the guest is dormant or has opted out. Sets status to 'Not Planted' and stops all auto-progression.")),
            ],
            options={
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='GuestEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('custom_id', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('title', models.CharField(choices=[('Chief', 'Chief'), ('Dr.', 'Dr.'), ('Engr.', 'Engr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.'), ('Pastor', 'Pastor'), ('Prof.', 'Prof.')], max_length=20)),
                ('full_name', models.CharField(db_index=True, max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('date_of_birth', models.CharField(blank=True, null=True)),
                ('birthday_month', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('birthday_day', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('age_range', models.CharField(blank=True, choices=[('Under 18', 'Under 18'), ('18–25', '18–25'), ('26–35', '26–35'), ('36–45', '36–45'), ('46 and Above', '46 and Above')], max_length=20)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married')], max_length=20)),
                ('home_address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('date_of_visit', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('first_thankyou_sent', models.BooleanField(default=False)),
                ('second_thankyou_sent', models.BooleanField(default=False)),
                ('second_visit_date', models.DateField(blank=True, db_index=True, null=True)),
                ('first_contact_reminder_sent', models.BooleanField(default=False, help_text='Set when the 3-day pre-reminder is sent to the officer.')),
                ('in_contact_overdue_notified', models.BooleanField(default=False, help_text='Set when the 7-day overdue notification is sent to the unit head.')),
                ('referred_by_name', models.CharField(blank=True, help_text='Name of the person who invited this guest (if not a member, or not yet).', max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuestStatus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='Used by the pipeline to identify this status. Do not change once set.')),
                ('color', models.CharField(default='gray', max_length=30)),
                ('is_default', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False, help_text='If True, the pipeline will not auto-progress this guest further.')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('in_training', 'In training'), ('passed', 'Passed'), ('inducted', 'Inducted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('inducted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTrack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('attendance_threshold', models.PositiveIntegerField(default=4, help_text="Number of services attended within the window to trigger 'Committed'.")),
                ('attendance_window_weeks', models.PositiveIntegerField(default=6, help_text='Rolling week window for attendance counting. e.g. 4 out of 6 weeks.')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MembershipTrackStep',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('comment', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('tiktok', 'Tiktok')], max_length=20)),
                ('handle', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VisitChannel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VisitPurpose',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationStepProgress',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_steps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
        ),
    ]
