# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('guests', '0001_initial'),
        ('permissions', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='followupreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guests', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='converted_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_origin', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='referred_by_member',
            field=models.ForeignKey(blank=True, help_text='Select if the person who invited this guest is already a member.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_guests', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='service_attended',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.churchservice'),
        ),
        migrations.AddField(
            model_name='followupreport',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='gueststatus',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='guests.gueststatus'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_applications', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='inducted_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_application', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='preferred_unit',
            field=models.ForeignKey(blank=True, help_text='The unit the applicant has chosen to serve in after induction.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_applicants', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationstepprogress',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_progress', to='guests.membershipapplication'),
        ),
        migrations.AddField(
            model_name='membershiptrack',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='guests.membershiptrack'),
        ),
        migrations.AddField(
            model_name='membershiptrackstep',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='membershiptrackstep',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='guests.membershiptrack'),
        ),
        migrations.AddField(
            model_name='applicationstepprogress',
            name='step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='guests.membershiptrackstep'),
        ),
        migrations.AddField(
            model_name='review',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='review',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='review',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='guests.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='review',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.unitrole'),
        ),
        migrations.AddField(
            model_name='socialmediaentry',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='socialmediaentry',
            name='guest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_accounts', to='guests.guestentry'),
        ),
        migrations.AddField(
            model_name='visitchannel',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='channel_of_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.visitchannel'),
        ),
        migrations.AddField(
            model_name='visitpurpose',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='guestentry',
            name='purpose_of_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guests.visitpurpose'),
        ),
        migrations.AddIndex(
            model_name='churchservice',
            index=models.Index(fields=['church', 'order'], name='guests_chur_church__0a0c23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='churchservice',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='followupreport',
            index=models.Index(fields=['church', 'report_date'], name='guests_foll_church__f6f09e_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreport',
            index=models.Index(fields=['church', 'assigned_to'], name='guests_foll_church__d29fce_idx'),
        ),
        migrations.AddIndex(
            model_name='followupreport',
            index=models.Index(fields=['church', 'guest', 'report_date'], name='guests_foll_church__e4300b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='followupreport',
            unique_together={('guest', 'report_date')},
        ),
        migrations.AddIndex(
            model_name='gueststatus',
            index=models.Index(fields=['church', 'order'], name='guests_gues_church__f49e3d_idx'),
        ),
        migrations.AddIndex(
            model_name='gueststatus',
            index=models.Index(fields=['church', 'slug'], name='guests_gues_church__3f3199_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='gueststatus',
            unique_together={('church', 'name'), ('church', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='membershiptrack',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['church', 'status'], name='guests_memb_church__8e2357_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipapplication',
            index=models.Index(fields=['church', 'track', 'status'], name='guests_memb_church__36b9e8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='membershipapplication',
            unique_together={('church', 'guest', 'track')},
        ),
        migrations.AlterUniqueTogether(
            name='membershiptrackstep',
            unique_together={('church', 'track', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='applicationstepprogress',
            unique_together={('application', 'step')},
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['church', 'created_at'], name='guests_revi_church__f0690d_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['guest', 'created_at'], name='guests_revi_guest_i_5c0733_idx'),
        ),
        migrations.AddIndex(
            model_name='socialmediaentry',
            index=models.Index(fields=['church', 'guest'], name='guests_soci_church__ab719b_idx'),
        ),
        migrations.AddIndex(
            model_name='visitchannel',
            index=models.Index(fields=['church', 'order'], name='guests_visi_church__8ea322_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitchannel',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='visitpurpose',
            index=models.Index(fields=['church', 'order'], name='guests_visi_church__cc5b38_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitpurpose',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'created_at'], name='guests_gues_church__fe349f_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'status'], name='guests_gues_church__d4c149_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'assigned_to'], name='guests_gues_church__7cd83a_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'date_of_visit'], name='guests_gues_church__634629_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'phone_number'], name='guests_gues_church__a9fa86_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'email'], name='guests_gues_church__3e12ca_idx'),
        ),
        migrations.AddIndex(
            model_name='guestentry',
            index=models.Index(fields=['church', 'birthday_month', 'birthday_day'], name='guests_gues_church__4f36f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestentry',
            constraint=models.UniqueConstraint(fields=('church', 'custom_id'), name='unique_guest_custom_id_per_church'),
        ),
    ]
