# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('growth_stage', models.CharField(blank=True, db_index=True, help_text='Optional campus growth stage label (configurable per church).', max_length=50)),
                ('contributes_to_parent_metrics', models.BooleanField(default=True, help_text='If True, this campus guest/attendance counts roll up to the parent campus metrics report.')),
                ('campus_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_campuses', to='accounts.churchmember')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('report_to', models.ForeignKey(blank=True, help_text='Parent campus this campus reports to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_campuses', to='units.campus')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CampusMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text="The member's primary campus (home base).")),
                ('notes', models.TextField(blank=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='units.campus')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campus_memberships', to='accounts.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='ChurchUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('unit_type', models.CharField(choices=[('unit', 'Unit / Department'), ('group', 'Group / Team')], db_index=True, default='unit', help_text="'Unit' for departments; 'Group' for cross-unit cohorts.", max_length=10)),
                ('guest_management', models.BooleanField(default=False, help_text='Enable guest management features for this unit.')),
                ('music_module', models.BooleanField(default=False, help_text='Enable music module features for this unit.')),
                ('media_module', models.BooleanField(default=False, help_text='Enable media module features for this unit.')),
                ('children_module', models.BooleanField(default=False, help_text='Enable children ministry features for this unit.')),
                ('youth_module', models.BooleanField(default=False, help_text='Enable youth ministry features for this unit.')),
                ('teenagers_module', models.BooleanField(default=False, help_text='Enable teenagers ministry features for this unit.')),
                ('is_default', models.BooleanField(default=False, help_text='New members are automatically assigned to default units.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('report_to', models.ForeignKey(blank=True, help_text='Parent unit this unit reports to (e.g. a zone or pastoral office).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='units.churchunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('unit', 'Unit Room'), ('project', 'Project Room'), ('private', 'Private Conversation')], db_index=True, default='unit', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='The primary room for a unit. Auto-created when a unit is created.')),
                ('description', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to='accounts.churchmember')),
                ('unit', models.ForeignKey(blank=True, help_text='The unit or group this room belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='units.churchunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChatRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_private_chats', to='accounts.churchmember')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_private_chats', to='accounts.churchmember')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to='units.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='UnitAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('session', models.CharField(blank=True, help_text="e.g. 'Weekly rehearsal', 'Task: Sound check', 'Leadership meeting'", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_attendance_marks', to='accounts.churchmember')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='units.churchunit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_probation', models.BooleanField(default=False, help_text='Member is on probation — limited to trainee-tier access.')),
                ('is_unit_head', models.BooleanField(default=False, help_text='This member is the head of the unit.')),
                ('consecutive_absences', models.PositiveSmallIntegerField(default=0, help_text='Resets on any attendance; triggers review at 2.')),
                ('for_review', models.BooleanField(db_index=True, default=False, help_text='Set True when 2 consecutive absences are recorded.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
        ),
    ]
