# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitReport',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('service', 'Service Report'), ('task', 'Task Report'), ('training', 'Training Report')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('copy_pastor', models.BooleanField(default=False, help_text='When enabled, notify active Pastor role holders globally.')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='submitted', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitTask',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('task_type', models.CharField(choices=[('single', 'Single Assignee'), ('group', 'Group Task')], db_index=True, default='single', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchUnit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, help_text='Auto-generated from name if left blank.')),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(default='blue', max_length=20)),
                ('unit_type', models.CharField(choices=[('unit', 'Unit / Department'), ('group', 'Group / Team')], db_index=True, default='unit', help_text="'Unit' for departments; 'Group' for cross-unit cohorts.", max_length=10)),
                ('guest_management', models.BooleanField(default=False, help_text='Enable guest management features for this unit.')),
                ('music_module', models.BooleanField(default=False, help_text='Enable music module features for this unit.')),
                ('media_module', models.BooleanField(default=False, help_text='Enable media module features for this unit.')),
                ('children_module', models.BooleanField(default=False, help_text='Enable children ministry features for this unit.')),
                ('youth_module', models.BooleanField(default=False, help_text='Enable youth ministry features for this unit.')),
                ('teenagers_module', models.BooleanField(default=False, help_text='Enable teenagers ministry features for this unit.')),
                ('is_default', models.BooleanField(default=False, help_text='New members are automatically assigned to default units.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('report_to', models.ForeignKey(blank=True, help_text='Parent unit this unit reports to (e.g. a zone or pastoral office).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_units', to='units.churchunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('unit', 'Unit Room'), ('project', 'Project Room'), ('private', 'Private Conversation')], db_index=True, default='unit', max_length=10)),
                ('is_default', models.BooleanField(default=False, help_text='The primary room for a unit. Auto-created when a unit is created.')),
                ('description', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to='accounts.churchmember')),
                ('members', models.ManyToManyField(blank=True, help_text='Explicit member list for sub-rooms. Leave empty for unit rooms.', related_name='joined_chat_rooms', to='accounts.churchmember')),
                ('parent_room', models.ForeignKey(blank=True, help_text='Set on sub-rooms (project type); null on top-level unit rooms.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_rooms', to='units.chatroom')),
                ('unit', models.ForeignKey(blank=True, help_text='The unit or group this room belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_rooms', to='units.churchunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PrivateChatRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_private_chats', to='accounts.churchmember')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_private_chats', to='accounts.churchmember')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_sessions', to='units.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('done', 'Done')], db_index=True, default='open', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_note', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
        ),
        migrations.CreateModel(
            name='UnitAnnouncement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('pinned_at', models.DateTimeField(blank=True, null=True)),
                ('is_banner', models.BooleanField(default=False, help_text='Show as scrolling banner on dashboard.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_announcements', to='accounts.churchmember')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='units.churchunit')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('excused', 'Excused')], default='absent', max_length=10)),
                ('session', models.CharField(blank=True, help_text="e.g. 'Weekly rehearsal', 'Task: Sound check', 'Leadership meeting'", max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_attendance_marks', to='accounts.churchmember')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='units.churchunit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UnitFunctionalRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('preset', models.CharField(choices=[('music_director', 'Music Director'), ('guitarist', 'Guitarist'), ('bassist', 'Bassist'), ('drummer', 'Drummer'), ('vocalist', 'Vocalist'), ('backup_vocalist', 'Backup Vocalist'), ('secretary', 'Secretary'), ('custom', 'Custom')], db_index=True, default='custom', help_text="Built-in preset slug, or 'custom' for user-defined roles.", max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_roles', to='units.churchunit')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitFunctionalRoleAssignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment_type', models.CharField(choices=[('permanent', 'Permanent'), ('period', 'For a Period'), ('event', 'For an Event')], db_index=True, default='permanent', max_length=15)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functional_role_assignments_made', to='accounts.churchmember')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='functional_role_assignments', to='services.event')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='units.unitfunctionalrole')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('is_probation', models.BooleanField(default=False, help_text='Member is on probation — limited to trainee-tier access.')),
                ('is_unit_head', models.BooleanField(default=False, help_text='This member is the head of the unit.')),
                ('is_assistant', models.BooleanField(default=False, help_text='This member assists the unit head. Gets tier-4 (Assistant) permissions automatically via the resolver, even without an explicit WorkforceRole.')),
                ('consecutive_absences', models.PositiveSmallIntegerField(default=0, help_text='Resets on any attendance; triggers review at 2.')),
                ('for_review', models.BooleanField(db_index=True, default=False, help_text='Set True when 2 consecutive absences are recorded.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
        ),
    ]
