# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmembership',
            name='trainee_profile',
            field=models.ForeignKey(blank=True, help_text='Trainee profile, used during probation or induction.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='workforce.workforcetraineeprofile'),
        ),
        migrations.AddField(
            model_name='unitmembership',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='unitmembership',
            name='workforce_member',
            field=models.ForeignKey(blank=True, help_text='Full workforce member. Null if member is still a trainee.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='workforce.workforcemember'),
        ),
        migrations.AddField(
            model_name='unitfunctionalroleassignment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='functional_role_assignments', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unitattendancerecord',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_attendance_records', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='report_to_unit',
            field=models.ForeignKey(blank=True, help_text='Next unit/group in the reporting chain.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_reports', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_unit_reports', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reports', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='unittask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_assignee_tasks', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unittask',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='group_tasks', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unittask',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='unittask',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unit_tasks', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='unittask',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='unitreport',
            name='related_task',
            field=models.ForeignKey(blank=True, help_text='Optional link to a specific unit task.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='units.unittask'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='units.unittask'),
        ),
        migrations.AddIndex(
            model_name='churchunit',
            index=models.Index(fields=['church', 'name'], name='units_churc_church__d043c1_idx'),
        ),
        migrations.AddIndex(
            model_name='churchunit',
            index=models.Index(fields=['church', 'unit_type'], name='units_churc_church__cc870d_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchunit',
            constraint=models.UniqueConstraint(fields=('church', 'slug'), name='unique_unit_slug_per_church'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['church', 'unit'], name='units_chatr_church__6f76b4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['church', 'room_type'], name='units_chatr_church__27c220_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['church', 'parent_room'], name='units_chatr_church__c6f25a_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatrequest',
            index=models.Index(fields=['church', 'is_active'], name='units_priva_church__a9ef19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechatrequest',
            unique_together={('room', 'requester', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='unitannouncement',
            index=models.Index(fields=['church', 'unit', '-created_at'], name='units_unita_church__d02069_idx'),
        ),
        migrations.AddIndex(
            model_name='unitannouncement',
            index=models.Index(fields=['church', 'unit', 'is_pinned'], name='units_unita_church__7fa0a4_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalrole',
            index=models.Index(fields=['church', 'unit'], name='units_unitf_church__8a33fe_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalrole',
            index=models.Index(fields=['church', 'unit', 'preset'], name='units_unitf_church__188df5_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalrole',
            index=models.Index(fields=['church', 'unit', 'is_active'], name='units_unitf_church__2383cc_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitfunctionalrole',
            constraint=models.UniqueConstraint(fields=('church', 'unit', 'name'), name='unique_functional_role_per_unit'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'unit'], name='units_unitm_church__6f2109_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'workforce_member'], name='units_unitm_church__2427e7_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'is_probation'], name='units_unitm_church__2f26ce_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'for_review'], name='units_unitm_church__12f068_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('workforce_member__isnull', False)), fields=('workforce_member', 'unit'), name='unique_unit_membership'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('trainee_profile__isnull', False)), fields=('trainee_profile', 'unit'), name='unique_trainee_unit_membership'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalroleassignment',
            index=models.Index(fields=['church', 'membership'], name='units_unitf_church__f7bbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalroleassignment',
            index=models.Index(fields=['church', 'role'], name='units_unitf_church__5dc994_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalroleassignment',
            index=models.Index(fields=['church', 'event'], name='units_unitf_church__064544_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalroleassignment',
            index=models.Index(fields=['church', 'is_active'], name='units_unitf_church__f0bd31_idx'),
        ),
        migrations.AddIndex(
            model_name='unitfunctionalroleassignment',
            index=models.Index(fields=['church', 'membership', 'is_active'], name='units_unitf_church__7424b3_idx'),
        ),
        migrations.AddIndex(
            model_name='unitattendancerecord',
            index=models.Index(fields=['church', 'unit', 'date'], name='units_unita_church__add2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='unitattendancerecord',
            index=models.Index(fields=['church', 'membership', '-date'], name='units_unita_church__4db283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitattendancerecord',
            unique_together={('membership', 'date', 'session')},
        ),
        migrations.AddIndex(
            model_name='unittask',
            index=models.Index(fields=['church', 'unit', 'task_type'], name='units_unitt_church__6f2f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='unittask',
            index=models.Index(fields=['church', 'unit', '-created_at'], name='units_unitt_church__1b9654_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreport',
            index=models.Index(fields=['church', 'unit', '-created_at'], name='units_unitr_church__f0aaca_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreport',
            index=models.Index(fields=['church', 'status'], name='units_unitr_church__52e553_idx'),
        ),
        migrations.AddIndex(
            model_name='unitreport',
            index=models.Index(fields=['church', 'category'], name='units_unitr_church__e77414_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['church', 'status'], name='units_taska_church__c5091c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskassignment',
            unique_together={('task', 'membership')},
        ),
    ]
