# Generated by Django 5.2.4 on 2026-03-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmembership',
            name='trainee_profile',
            field=models.ForeignKey(blank=True, help_text='Trainee profile, used during probation or induction.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='workforce.workforcetraineeprofile'),
        ),
        migrations.AddField(
            model_name='unitmembership',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='unitmembership',
            name='workforce_member',
            field=models.ForeignKey(blank=True, help_text='Full workforce member. Null if member is still a trainee.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_memberships', to='workforce.workforcemember'),
        ),
        migrations.AddField(
            model_name='unitattendancerecord',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_attendance_records', to='units.unitmembership'),
        ),
        migrations.AddIndex(
            model_name='campus',
            index=models.Index(fields=['church', 'growth_stage'], name='units_campu_church__4fb5e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='campus',
            constraint=models.UniqueConstraint(fields=('church', 'slug'), name='unique_campus_slug_per_church'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['church', 'campus'], name='units_campu_church__a5183c_idx'),
        ),
        migrations.AddIndex(
            model_name='campusmembership',
            index=models.Index(fields=['church', 'member'], name='units_campu_church__cf3d8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='campusmembership',
            constraint=models.UniqueConstraint(fields=('member', 'campus'), name='unique_campus_membership'),
        ),
        migrations.AddIndex(
            model_name='churchunit',
            index=models.Index(fields=['church', 'name'], name='units_churc_church__d043c1_idx'),
        ),
        migrations.AddIndex(
            model_name='churchunit',
            index=models.Index(fields=['church', 'unit_type'], name='units_churc_church__cc870d_idx'),
        ),
        migrations.AddConstraint(
            model_name='churchunit',
            constraint=models.UniqueConstraint(fields=('church', 'slug'), name='unique_unit_slug_per_church'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['church', 'unit'], name='units_chatr_church__6f76b4_idx'),
        ),
        migrations.AddIndex(
            model_name='chatroom',
            index=models.Index(fields=['church', 'room_type'], name='units_chatr_church__27c220_idx'),
        ),
        migrations.AddIndex(
            model_name='privatechatrequest',
            index=models.Index(fields=['church', 'is_active'], name='units_priva_church__a9ef19_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechatrequest',
            unique_together={('room', 'requester', 'recipient')},
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'unit'], name='units_unitm_church__6f2109_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'workforce_member'], name='units_unitm_church__2427e7_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'is_probation'], name='units_unitm_church__2f26ce_idx'),
        ),
        migrations.AddIndex(
            model_name='unitmembership',
            index=models.Index(fields=['church', 'for_review'], name='units_unitm_church__12f068_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('workforce_member__isnull', False)), fields=('workforce_member', 'unit'), name='unique_unit_membership'),
        ),
        migrations.AddConstraint(
            model_name='unitmembership',
            constraint=models.UniqueConstraint(condition=models.Q(('trainee_profile__isnull', False)), fields=('trainee_profile', 'unit'), name='unique_trainee_unit_membership'),
        ),
        migrations.AddIndex(
            model_name='unitattendancerecord',
            index=models.Index(fields=['church', 'unit', 'date'], name='units_unita_church__add2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='unitattendancerecord',
            index=models.Index(fields=['church', 'membership', '-date'], name='units_unita_church__4db283_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unitattendancerecord',
            unique_together={('membership', 'date', 'session')},
        ),
    ]
