# Generated by Django 5.2.4 on 2026-03-23 19:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('guests', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LMSCourseRequirement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('counts_for_promotion', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LMSEnrollment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('active', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn'), ('certified', 'Certified')], db_index=True, default='active', max_length=15)),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Overall computed score (0–100) at completion.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LMSModule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('text', 'Text / Reading'), ('video', 'Video'), ('pdf', 'PDF / Document'), ('attendance', 'Attendance Required'), ('assessment', 'Written Assessment'), ('practical', 'Practical / Task')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Text content, video embed URL, or instruction body.')),
                ('resource', cloudinary.models.CloudinaryField(blank=True, help_text='PDF, video, or other resource file.', max_length=255, null=True, verbose_name='lms_resource')),
                ('is_required', models.BooleanField(default=True, help_text='If False, this module is optional and does not block progression.')),
                ('requires_attachment', models.BooleanField(default=False, help_text='If True, submission must include a file attachment.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LMSReview',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('passed', models.BooleanField(help_text='True = submission passed; False = failed.')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score (0–100) assigned by the proctor.', null=True)),
                ('feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LMSSubmission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Under Review'), ('passed', 'Passed'), ('failed', 'Failed'), ('returned', 'Returned for Revision')], db_index=True, default='submitted', max_length=15)),
                ('content', models.TextField(blank=True, help_text='Written response, reflection, or report body.')),
                ('attachment', cloudinary.models.CloudinaryField(blank=True, help_text='Required for modules where requires_attachment=True.', max_length=255, null=True, verbose_name='lms_submission')),
                ('score', models.PositiveSmallIntegerField(blank=True, help_text='Score assigned by the proctor (0–100).', null=True)),
                ('retake_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LMSCertificate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('certificate_text', models.TextField(blank=True)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='Generated PDF certificate file.', max_length=255, null=True, verbose_name='lms_certificate')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to='accounts.churchmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LMSCourse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('induction', 'Member Induction'), ('unit_training', 'Unit Training'), ('workforce', 'Workforce-wide Training'), ('disciplinary', 'Disciplinary Program')], db_index=True, default='unit_training', max_length=20)),
                ('delivery_mode', models.CharField(choices=[('physical', 'Physical'), ('virtual', 'Virtual'), ('hybrid', 'Physical & Virtual')], default='physical', max_length=10)),
                ('passing_score', models.PositiveSmallIntegerField(default=70, help_text='Minimum score (0–100) to pass this course.')),
                ('allow_retake', models.BooleanField(default=True, help_text='Allow enrollees to retake a failed module.')),
                ('max_retakes', models.PositiveSmallIntegerField(default=2, help_text='Maximum number of retakes per module. 0 = unlimited.')),
                ('strict_sequence', models.BooleanField(default=True, help_text='If True, enrollee must pass each module before accessing the next.')),
                ('certificate_template', models.TextField(blank=True, help_text='Certificate text template. Use {name}, {course}, {date} as placeholders.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to='accounts.churchmember')),
                ('membership_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='guests.membershiptrack')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
