# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('lms', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lmscourse',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='If set, this course is specific to this unit. Leave blank for church-wide.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_courses', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms.lmscourse'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='enrolled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolled_members', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_enrollments', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='lmscertificate',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='lms.lmsenrollment'),
        ),
        migrations.AddField(
            model_name='lmsmodule',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='lmsmodule',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lms.lmscourse'),
        ),
        migrations.AddField(
            model_name='lmsenrollment',
            name='current_module',
            field=models.ForeignKey(blank=True, help_text='The module the enrollee is currently on.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enrollees', to='lms.lmsmodule'),
        ),
        migrations.AddField(
            model_name='lmsreview',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='lmsreview',
            name='proctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lms_reviews', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='lmssubmission',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='lmssubmission',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.lmsenrollment'),
        ),
        migrations.AddField(
            model_name='lmssubmission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='lms.lmsmodule'),
        ),
        migrations.AddField(
            model_name='lmsreview',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='lms.lmssubmission'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['church', 'course_type'], name='lms_lmscour_church__d4a494_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscourse',
            index=models.Index(fields=['church', 'unit'], name='lms_lmscour_church__facd3c_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscertificate',
            index=models.Index(fields=['church', '-created_at'], name='lms_lmscert_church__666bea_idx'),
        ),
        migrations.AddIndex(
            model_name='lmscertificate',
            index=models.Index(fields=['church', 'is_active'], name='lms_lmscert_church__c6cdb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='lmsmodule',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_module_order_per_course'),
        ),
        migrations.AddIndex(
            model_name='lmsenrollment',
            index=models.Index(fields=['church', 'status'], name='lms_lmsenro_church__2c21d2_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsenrollment',
            index=models.Index(fields=['church', 'course'], name='lms_lmsenro_church__5ea224_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmsenrollment',
            unique_together={('member', 'course')},
        ),
        migrations.AddIndex(
            model_name='lmssubmission',
            index=models.Index(fields=['church', 'status'], name='lms_lmssubm_church__39117c_idx'),
        ),
        migrations.AddIndex(
            model_name='lmssubmission',
            index=models.Index(fields=['church', 'module'], name='lms_lmssubm_church__45a724_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lmssubmission',
            unique_together={('enrollment', 'module', 'retake_count')},
        ),
        migrations.AddIndex(
            model_name='lmsreview',
            index=models.Index(fields=['church', '-created_at'], name='lms_lmsrevi_church__e5b2cc_idx'),
        ),
        migrations.AddIndex(
            model_name='lmsreview',
            index=models.Index(fields=['church', 'is_active'], name='lms_lmsrevi_church__577b5d_idx'),
        ),
    ]
