# Generated by Django 5.2.4 on 2026-05-27 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0007_alter_biblechaptercache_options_and_more'),
        ('lms', '0005_lms_template_reading_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lmsmodule',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text / Reading'), ('video', 'Video'), ('audio', 'Audio'), ('pdf', 'PDF / Document'), ('assessment', 'Written Assessment'), ('practical', 'Practical / Task'), ('quiz', 'Quiz'), ('link', 'External Link'), ('embed', 'Embedded Content'), ('reading_plan', 'Bible Reading Plan')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='lmsmodule',
            name='reading_plan',
            field=models.ForeignKey(blank=True, help_text='Link a Bible reading plan into this module. Members complete plan entries as part of the course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lms_modules', to='bible.readingplan'),
        ),
        migrations.AlterField(
            model_name='lmsmodule',
            name='template_type',
            field=models.CharField(choices=[('none', 'No Template (free-form)'), ('lesson', 'Lesson Page (Notion-style)'), ('case_study', 'Case Study'), ('reflection', 'Guided Reflection'), ('bible_devotional', 'Bible Devotional'), ('reading_plan_embed', 'Reading Plan Embed'), ('discussion_prompt', 'Discussion Prompt'), ('checklist', 'Action Checklist'), ('quiz_bank', 'Quiz / Question Bank')], default='none', help_text='When set, the admin populates this module via a structured template form. template_data stores the resulting JSON.', max_length=20),
        ),
    ]
