# Generated by Django 5.2.4 on 2026-03-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.CharField(choices=[('scheduler', 'Scheduler Job'), ('webhook', 'Webhook Event'), ('signal', 'Signal'), ('billing', 'Billing'), ('messaging', 'Messaging'), ('pipeline', 'Guest Pipeline'), ('system', 'System')], db_index=True, default='system', max_length=20)),
                ('event_type', models.CharField(db_index=True, help_text="e.g. 'birthday_sms_sent', 'charge.success', 'committed_guests_flagged'", max_length=100)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed'), ('info', 'Info')], db_index=True, default='info', max_length=20)),
                ('summary', models.CharField(blank=True, help_text='Human-readable one-line summary shown in the admin list.', max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Structured data for debugging — IDs, counts, error details.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'category', '-created_at'], name='automation__church__71b1ff_idx'), models.Index(fields=['church', 'status'], name='automation__church__f11d71_idx'), models.Index(fields=['church', 'event_type'], name='automation__church__548edd_idx')],
            },
        ),
    ]
