# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('guests', '0001_initial'),
        ('lms', '0001_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('activity_type', models.CharField(choices=[('followup', 'Follow-up'), ('message', 'Message Sent'), ('guest_view', 'Viewed Guest'), ('call', 'Called Guest'), ('report', 'Submitted Report'), ('other', 'Other')], max_length=50)),
                ('guest_id', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.churchmember')),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceMember',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('stage_updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workforce_profiles', to='accounts.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcemember')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='WorkforceRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('is_leadership', models.BooleanField(default=False)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkforceStage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'unique_together': {('church', 'name')},
            },
        ),
        migrations.AddField(
            model_name='workforcemember',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workforce.workforcestage'),
        ),
        migrations.CreateModel(
            name='WorkforceTraineeProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.CharField(choices=[('induction', 'New member induction'), ('probation', 'Disciplinary probation'), ('transfer', 'Campus/unit transfer (awaiting re-assignment)')], db_index=True, default='induction', max_length=20)),
                ('probation_ends_at', models.DateField(blank=True, help_text='For disciplinary probation — the date probation is due to end.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('lms_enrollment', models.ForeignKey(blank=True, help_text='The induction LMS course enrollment for this trainee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainee_profiles', to='lms.lmsenrollment')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainee_profiles', to='accounts.churchmember')),
                ('preferred_unit', models.ForeignKey(blank=True, help_text='The unit the trainee has indicated they wish to join.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_trainees', to='units.churchunit')),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_trainees', to='accounts.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('excused', 'Excused'), ('absent', 'Absent')], default='absent', max_length=10)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='services.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='units.unitmembership')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'event', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='chat_voice/')),
                ('file', models.CharField(blank=True, max_length=5000, null=True)),
                ('file_type', models.CharField(blank=True, max_length=5000, null=True)),
                ('file_name', models.CharField(blank=True, max_length=5000, null=True)),
                ('link_url', models.CharField(blank=True, max_length=5000, null=True)),
                ('link_title', models.CharField(blank=True, max_length=5000, null=True)),
                ('link_description', models.CharField(blank=True, max_length=5000, null=True)),
                ('link_image', models.TextField(blank=True, null=True)),
                ('pinned', models.BooleanField(db_index=True, default=False)),
                ('pinned_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('original_message', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to='units.unitmembership')),
                ('forwarded_from', models.ForeignKey(blank=True, help_text='Set when this message is a forward of another.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwards', to='workforce.chatmessage')),
                ('guest_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='guests.guestentry')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='workforce.chatmessage')),
                ('pinned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinned_messages', to='units.unitmembership')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_messages', to='units.unitmembership')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='units.chatroom')),
                ('seen_by', models.ManyToManyField(blank=True, related_name='seen_messages', to='units.unitmembership')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='units.unitmembership')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'created_at'], name='workforce_c_sender__c37537_idx'), models.Index(fields=['guest_card', 'created_at'], name='workforce_c_guest_c_9a31ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='ClockRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clock_records', to='services.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clock_records', to='units.unitmembership')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date', 'event')},
            },
        ),
        migrations.CreateModel(
            name='WorkforceMembershipRole',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('workforce_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='workforce.workforcemember')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.workforcerole')),
            ],
            options={
                'unique_together': {('workforce_member', 'role')},
            },
        ),
        migrations.AddIndex(
            model_name='workforcemember',
            index=models.Index(fields=['church', 'stage'], name='workforce_w_church__3381a5_idx'),
        ),
        migrations.AddConstraint(
            model_name='workforcemember',
            constraint=models.UniqueConstraint(fields=('church', 'member'), name='unique_workforce_member'),
        ),
        migrations.AddIndex(
            model_name='workforcetraineeprofile',
            index=models.Index(fields=['church', 'reason'], name='workforce_w_church__3f5322_idx'),
        ),
        migrations.AddIndex(
            model_name='workforcetraineeprofile',
            index=models.Index(fields=['church', 'is_active'], name='workforce_w_church__103d46_idx'),
        ),
        migrations.AddConstraint(
            model_name='workforcetraineeprofile',
            constraint=models.UniqueConstraint(fields=('church', 'member'), name='unique_trainee_per_church_member'),
        ),
    ]
