# Generated by Django 5.2.4 on 2026-05-12 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('workforce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('default_tier_list', models.JSONField(blank=True, default=list)),
                ('room_tier_overrides', models.JSONField(blank=True, default=dict)),
                ('bg_type', models.CharField(choices=[('logo', 'Church Logo (watermark)'), ('upload', 'Custom image'), ('none', 'No background')], default='logo', max_length=16)),
                ('bg_image', models.ImageField(blank=True, null=True, upload_to='chat_bg/')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'verbose_name': 'Chat Settings',
            },
        ),
    ]
