# Generated by Django 5.2.4 on 2026-05-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0003_chatmessagereaction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='chatmessagereaction',
            new_name='workforce_c_message_e51c14_idx',
            old_name='workforce_c_message_7b8c0e_idx',
        ),
        migrations.RenameIndex(
            model_name='chatmessagereaction',
            new_name='workforce_c_church__fb83cd_idx',
            old_name='workforce_c_church__2a1f8b_idx',
        ),
    ]
