# Generated by Django 5.2.4 on 2026-03-22 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('teenagers', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teenprofile',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teen_profiles', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='mentorassignment',
            name='teen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='teenagers.teenprofile'),
        ),
        migrations.AddField(
            model_name='trendpulse',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='trendpulse',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teen_trend_pulses', to='accounts.churchmember'),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['church', 'unit'], name='teenagers_t_church__e6c4e8_idx'),
        ),
        migrations.AddIndex(
            model_name='teenprofile',
            index=models.Index(fields=['church', 'full_name'], name='teenagers_t_church__634c53_idx'),
        ),
        migrations.AddIndex(
            model_name='mentorassignment',
            index=models.Index(fields=['church', 'mentor'], name='teenagers_m_church__6284bc_idx'),
        ),
        migrations.AddIndex(
            model_name='trendpulse',
            index=models.Index(fields=['church', 'topic'], name='teenagers_t_church__d83bdd_idx'),
        ),
    ]
