# Generated by Django 5.2.4 on 2026-05-09 09:57

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Short code: KJV, NIV, NLT, ESV, NKJV, MSG, AMP, …', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Full name.', max_length=100)),
                ('language', models.CharField(default='English', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('api_source', models.CharField(blank=True, help_text='Source API key or identifier.', max_length=60)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('slides', 'Presentation Slides'), ('lyric_video', 'Lyric Video'), ('video_clip', 'Video Clip'), ('lower_third', 'Lower Third'), ('background', 'Background Image'), ('audio', 'Audio File'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media_asset')),
                ('external_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PastorNote',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(blank=True, help_text='Message title.', max_length=255)),
                ('series_title', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(help_text='Sermon notes, key scriptures, outline.')),
                ('scripture_refs', models.JSONField(blank=True, default=list, help_text='List of scripture references for auto-slide generation.')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PresentationSlide',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide_type', models.CharField(choices=[('lyric', 'Lyric'), ('scripture', 'Scripture'), ('title', 'Title / Announcement'), ('blank', 'Blank'), ('image', 'Full-Screen Image'), ('video', 'Full-Screen Video')], db_index=True, default='lyric', max_length=20)),
                ('content', models.TextField(blank=True, help_text='Main slide text.')),
                ('sub_content', models.CharField(blank=True, help_text='Secondary text (reference, subtitle).', max_length=300)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='slide_img')),
                ('video_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='track title, section label, song order, etc.')),
                ('is_auto', models.BooleanField(default=False, help_text='True if auto-generated from setlist sync.')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Pending Review'), ('ready', 'Ready'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('slides_ready', models.BooleanField(default=False)),
                ('audio_ready', models.BooleanField(default=False)),
                ('video_ready', models.BooleanField(default=False)),
                ('broadcast_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePresentation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('is_live', models.BooleanField(default=False, help_text='True when actively being projected.')),
                ('current_slide_index', models.PositiveIntegerField(default=0, help_text="Presenter's current slide position.")),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('lyrics', 'Lyrics'), ('scripture', 'Scripture'), ('title', 'Title/Announcement'), ('blank', 'Blank'), ('custom', 'Custom')], default='lyrics', max_length=20)),
                ('background', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='slide_bg')),
                ('background_color', models.CharField(default='#000000', max_length=7)),
                ('text_color', models.CharField(default='#ffffff', max_length=7)),
                ('font_family', models.CharField(default='sans-serif', max_length=60)),
                ('font_size', models.PositiveIntegerField(default=48, help_text='Base font size in px.')),
                ('overlay_opacity', models.FloatField(default=0.4, help_text='Dark overlay on background image (0–1).')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Advanced: padding, line-height, shadow, etc.')),
                ('is_default', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=False, help_text="System templates can't be deleted.")),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BiblePassage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reference', models.CharField(db_index=True, help_text='e.g. John 3:16 or Psalm 23:1-6', max_length=100)),
                ('text', models.TextField()),
                ('bible_slides', models.JSONField(blank=True, default=list, help_text="List of strings; each element = one slide's text.")),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passages', to='media.bibleversion')),
            ],
        ),
        migrations.CreateModel(
            name='BroadcastConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_streaming', models.BooleanField(default=False)),
                ('stream_platform', models.CharField(blank=True, max_length=50)),
                ('stream_url', models.URLField(blank=True)),
                ('stream_key', models.CharField(blank=True, max_length=255)),
                ('youtube_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
