# Generated by Django 5.2.4 on 2026-03-23 19:51

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('asset_type', models.CharField(choices=[('slides', 'Presentation Slides'), ('lyric_video', 'Lyric Video'), ('video_clip', 'Video Clip'), ('lower_third', 'Lower Third'), ('background', 'Background Image'), ('audio', 'Audio File'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('file', cloudinary.models.CloudinaryField(blank=True, help_text='Upload the asset file (PDF, image, video, audio).', max_length=255, null=True, verbose_name='media_asset')),
                ('external_url', models.URLField(blank=True, help_text='External link (e.g. Google Slides, YouTube, Dropbox).')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductionSchedule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('review', 'Pending Review'), ('ready', 'Ready'), ('completed', 'Completed')], db_index=True, default='draft', max_length=20)),
                ('slides_ready', models.BooleanField(default=False)),
                ('audio_ready', models.BooleanField(default=False)),
                ('video_ready', models.BooleanField(default=False)),
                ('broadcast_ready', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastConfig',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_streaming', models.BooleanField(default=False)),
                ('stream_platform', models.CharField(blank=True, help_text='e.g. YouTube, Facebook, Twitch, Custom RTMP', max_length=50)),
                ('stream_url', models.URLField(blank=True)),
                ('stream_key', models.CharField(blank=True, help_text='RTMP stream key — treat as sensitive.', max_length=255)),
                ('is_recording', models.BooleanField(default=False)),
                ('recording_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
