# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_initial'),
        ('media', '0002_initial'),
        ('music', '0002_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastconfig',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_configs', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='pastornote',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastor_notes', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='pastornote',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='pastornote',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pastor_notes', to='services.event'),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='bible_passage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='media.biblepassage'),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='lyrics_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='music.lyricssection'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_schedule', to='services.event'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_schedules', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_schedules', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='media.productionschedule'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_presentations', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation', to='services.event'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='setlist',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentation', to='music.setlist'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='presentation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='media.servicepresentation'),
        ),
        migrations.AddField(
            model_name='pastornote',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pastor_notes', to='media.servicepresentation'),
        ),
        migrations.AddField(
            model_name='slidetemplate',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='servicepresentation',
            name='default_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presentations', to='media.slidetemplate'),
        ),
        migrations.AddField(
            model_name='presentationslide',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slides', to='media.slidetemplate'),
        ),
        migrations.AddIndex(
            model_name='biblepassage',
            index=models.Index(fields=['church', 'version'], name='media_bible_church__ba5b65_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='biblepassage',
            unique_together={('church', 'version', 'reference')},
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['church', 'status'], name='media_produ_church__65c1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['church', 'unit'], name='media_produ_church__9221e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['church', 'asset_type'], name='media_media_church__31d004_idx'),
        ),
        migrations.AddIndex(
            model_name='pastornote',
            index=models.Index(fields=['church', 'event'], name='media_pasto_church__79649c_idx'),
        ),
        migrations.AddIndex(
            model_name='pastornote',
            index=models.Index(fields=['church', 'presentation'], name='media_pasto_church__c138f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='slidetemplate',
            unique_together={('church', 'name')},
        ),
        migrations.AddIndex(
            model_name='servicepresentation',
            index=models.Index(fields=['church', 'event'], name='media_servi_church__a3120b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepresentation',
            index=models.Index(fields=['church', 'unit'], name='media_servi_church__a822ad_idx'),
        ),
    ]
