# Generated by Django 5.2.4 on 2026-03-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('media', '0002_initial'),
        ('services', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastconfig',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcast_configs', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assets', to='accounts.churchmember'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='production_schedule', to='services.event'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='prepared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_schedules', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='productionschedule',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='The media/production unit responsible for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_schedules', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='media.productionschedule'),
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['church', 'status'], name='media_produ_church__65c1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='productionschedule',
            index=models.Index(fields=['church', 'unit'], name='media_produ_church__9221e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaasset',
            index=models.Index(fields=['church', 'asset_type'], name='media_media_church__31d004_idx'),
        ),
    ]
