# Generated by Django 5.2.4 on 2026-03-23 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permissions', '0001_initial'),
        ('tenants', '0001_initial'),
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershiprole',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='units.unitmembership'),
        ),
        migrations.AddField(
            model_name='unitrole',
            name='church',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church'),
        ),
        migrations.AddField(
            model_name='unitrole',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='units.churchunit'),
        ),
        migrations.AddField(
            model_name='membershiprole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='permissions.unitrole'),
        ),
        migrations.AddIndex(
            model_name='unitrole',
            index=models.Index(fields=['church', 'unit'], name='permissions_church__ed3520_idx'),
        ),
        migrations.AddConstraint(
            model_name='unitrole',
            constraint=models.UniqueConstraint(fields=('church', 'unit', 'name'), name='unique_unit_role_per_unit'),
        ),
        migrations.AddConstraint(
            model_name='membershiprole',
            constraint=models.UniqueConstraint(fields=('membership', 'role'), name='unique_role_per_membership'),
        ),
    ]
