# Generated by Django 5.2.4 on 2026-05-09 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_urgent', models.BooleanField(default=False)),
                ('is_success', models.BooleanField(default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(blank=True, db_index=True, help_text='If set, the push notification is deferred until this time.', null=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.churchmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['church', 'member', '-created_at'], name='notificatio_church__b7fdba_idx'), models.Index(fields=['church', 'is_read'], name='notificatio_church__0a2dd9_idx'), models.Index(fields=['send_at'], name='notificatio_send_at_2ebbee_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subscription_data', models.JSONField(help_text='Endpoint and VAPID keys from the browser.')),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to='accounts.churchmember')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['church', '-created_at'], name='notificatio_church__0f7fab_idx'), models.Index(fields=['church', 'is_active'], name='notificatio_church__0abef0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notification_sound', models.CharField(choices=[('chime1', 'Chime 1'), ('chime2', 'Chime 2'), ('chime3', 'Chime 3'), ('chime4', 'Chime 4'), ('chime5', 'Chime 5'), ('chime6', 'Chime 6'), ('chime7', 'Chime 7'), ('chime8', 'Chime 8')], default='chime1', max_length=20)),
                ('vibration_enabled', models.BooleanField(default=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='tenants.church')),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.churchmember')),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['church', '-created_at'], name='notificatio_church__3d5128_idx'), models.Index(fields=['church', 'is_active'], name='notificatio_church__b2820c_idx')],
            },
        ),
    ]
